"""
AgentStack Terminal Server
==========================

WebSocket-based terminal server that bridges xterm.js ↔ PTY sessions.

Architecture:
  Telegram Mini App (xterm.js) → WebSocket → FastAPI → PTY (via tmux)

Key features:
  - tmux backend: sessions persist across server restarts
  - 64KB replay buffer: reconnecting clients get terminal state back
  - ping/pong keepalive (20s): detects dead mobile connections
  - Per-agent MCP configs: each agent launches with specific tools
  - File upload/download: REST endpoints for drag-and-drop transfer
  - Device Attribute filtering: strips xterm.js DA responses that leak as ghost text

Auth:
  Single-owner model. First WebSocket message must be a valid HMAC token
  generated by the Telegram bot (see users.py).

Usage:
  python3 web/server.py                    # direct
  uvicorn web.server:app --host 0.0.0.0    # via uvicorn
"""

import asyncio
import glob as glob_mod
import json
import logging
import os
import platform
import pty
import re
import select
import shlex
import shutil
import signal
import struct
import subprocess
import sys
import fcntl
import termios
import time
from pathlib import Path

from contextlib import asynccontextmanager

from fastapi import FastAPI, WebSocket, WebSocketDisconnect, UploadFile, File, Form, Request
from fastapi.staticfiles import StaticFiles
from fastapi.responses import RedirectResponse, FileResponse, JSONResponse

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import users

log = logging.getLogger("agentstack.web")

AGENTS_FILE = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))) / "agents.json"
PROJECT_DIR = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
START_TIME = time.time()
UPLOAD_DIR = Path(os.path.expanduser("~")) / "uploads"

# tmux session prefix — avoids collision with user's own tmux sessions
TMUX_PREFIX = "as_"

# Cached agents.json with mtime check
_agents_cache = {}
_agents_mtime = 0.0

# Use tmux if available, fall back to raw PTY
HAS_TMUX = shutil.which("tmux") is not None


def load_agents() -> dict:
    global _agents_cache, _agents_mtime
    try:
        mt = AGENTS_FILE.stat().st_mtime
        if mt != _agents_mtime:
            with open(AGENTS_FILE) as f:
                _agents_cache = json.load(f).get("agents", {})
            _agents_mtime = mt
    except FileNotFoundError:
        _agents_cache = {}
    return _agents_cache


# Env vars to strip — prevents nested Claude Code sessions from inheriting parent state
_STRIP_ENV = ("CLAUDECODE", "CLAUDE_CODE", "CLAUDE_SESSION")

# Session name sanitizer
_NAME_RE = re.compile(r'[^a-z0-9_-]')


def _sanitize_name(name: str) -> str:
    return _NAME_RE.sub('', name.lower().strip())[:32]


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup
    UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
    asyncio.create_task(_reap_loop())
    if HAS_TMUX:
        existing = tmux_list_sessions()
        if existing:
            log.info("Found %d existing tmux sessions: %s", len(existing), existing)
    yield
    # Shutdown — detach PTY sessions, leave tmux sessions alive
    log.info("Shutting down — detaching PTY sessions (tmux sessions persist)")
    for s in pool.sessions.values():
        s._alive = False
        if s.fd >= 0:
            try:
                os.close(s.fd)
            except OSError:
                pass
        if s.pid > 0:
            try:
                os.kill(s.pid, signal.SIGTERM)
            except (OSError, ChildProcessError):
                pass
    pool.sessions.clear()


app = FastAPI(title="AgentStack Terminal", lifespan=lifespan)
app.mount("/static", StaticFiles(directory=os.path.join(os.path.dirname(__file__), "static")), name="static")

# Replay buffer size per session (64KB for rich terminal state on reconnect)
REPLAY_BUFFER_SIZE = 65536


# ── tmux helpers ─────────────────────────────────────────

def tmux_session_name(name: str) -> str:
    return f"{TMUX_PREFIX}{name}"


def tmux_list_sessions() -> list[str]:
    """List active tmux sessions with our prefix."""
    if not HAS_TMUX:
        return []
    try:
        result = subprocess.run(
            ["tmux", "list-sessions", "-F", "#{session_name}"],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode != 0:
            return []
        names = []
        for line in result.stdout.strip().split("\n"):
            line = line.strip()
            if line.startswith(TMUX_PREFIX):
                names.append(line[len(TMUX_PREFIX):])
        return names
    except Exception:
        return []


def tmux_create_session(name: str, cmd: list[str], cwd: str, env_extra: dict = None):
    """Create a detached tmux session."""
    sess = tmux_session_name(name)
    env = os.environ.copy()
    env["TERM"] = "xterm-256color"
    env["COLORTERM"] = "truecolor"
    for var in _STRIP_ENV:
        env.pop(var, None)
    if env_extra:
        env.update(env_extra)

    # Build the shell command string with proper quoting
    shell_cmd = shlex.join(cmd)

    subprocess.run(
        ["tmux", "new-session", "-d", "-s", sess, "-x", "120", "-y", "35", shell_cmd],
        cwd=cwd, env=env, timeout=10,
        capture_output=True
    )


def tmux_kill_session(name: str):
    """Kill a tmux session."""
    sess = tmux_session_name(name)
    try:
        subprocess.run(["tmux", "kill-session", "-t", sess], capture_output=True, timeout=5)
    except Exception:
        pass


_WSH_PATHS = [
    shutil.which("wsh"),
    os.path.expanduser("~/.local/share/waveterm/bin/wsh"),
    os.path.expanduser("~/snap/waveterm/current/.local/share/waveterm/bin/wsh"),
]
# Find wsh at startup (snap installs it outside PATH)
for _p in _WSH_PATHS:
    if _p and os.path.isfile(_p):
        WSH_BIN = _p
        break
else:
    WSH_BIN = None


def mirror_to_wave(session_name: str) -> bool:
    """Mirror a tmux session to a Wave terminal block if Wave is running.

    Returns True if Wave was found and wsh was invoked, False otherwise.
    Silently skips if Wave is not running or wsh is not available.
    """
    if not WSH_BIN:
        log.debug("wsh not found — skipping Wave mirror")
        return False
    try:
        result = subprocess.run(
            ["pgrep", "wavesrv"],
            capture_output=True, timeout=3
        )
        if result.returncode != 0:
            log.debug("Wave not running — skipping mirror")
            return False
    except Exception:
        return False

    sess = tmux_session_name(session_name)
    try:
        subprocess.Popen(
            [WSH_BIN, "run", "--", "tmux", "attach", "-t", sess],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        log.info("Mirrored session '%s' to Wave", sess)
        return True
    except Exception as e:
        log.warning("Wave mirror failed for '%s': %s", sess, e)
        return False


def tmux_session_exists(name: str) -> bool:
    """Check if a tmux session exists."""
    sess = tmux_session_name(name)
    try:
        result = subprocess.run(
            ["tmux", "has-session", "-t", sess],
            capture_output=True, timeout=5
        )
        return result.returncode == 0
    except Exception:
        return False


# ── PTY Session (attaches to tmux or runs raw) ──────────

class PtySession:
    def __init__(self, name: str, cmd: list[str], cwd: str = None, env_extra: dict = None, use_tmux: bool = True):
        self.name = name
        self.pid = -1
        self.fd = -1
        self._alive = False
        self.replay_buffer = bytearray()
        self.uses_tmux = use_tmux and HAS_TMUX
        self.cwd = cwd or os.path.expanduser("~")

        os.makedirs(self.cwd, exist_ok=True)

        env = os.environ.copy()
        env["TERM"] = "xterm-256color"
        env["COLORTERM"] = "truecolor"
        for var in _STRIP_ENV:
            env.pop(var, None)
        if env_extra:
            env.update(env_extra)

        if self.uses_tmux:
            # Create tmux session if it doesn't exist
            if not tmux_session_exists(name):
                tmux_create_session(name, cmd, self.cwd, env_extra)
                time.sleep(0.3)
                # Wait for tmux session to be ready before mirroring
                ready = False
                for _ in range(6):
                    if tmux_session_exists(name):
                        ready = True
                        break
                    time.sleep(0.2)
                if ready:
                    mirror_to_wave(name)
            else:
                # Session already exists — mirror to Wave on re-attach too
                mirror_to_wave(name)

            # Attach to tmux session via PTY
            attach_cmd = ["tmux", "attach", "-t", tmux_session_name(name)]
            self.pid, self.fd = pty.fork()
            if self.pid == 0:
                os.chdir(self.cwd)
                os.execvpe(attach_cmd[0], attach_cmd, env)
            else:
                self._alive = True
                flags = fcntl.fcntl(self.fd, fcntl.F_GETFL)
                fcntl.fcntl(self.fd, fcntl.F_SETFL, flags | os.O_NONBLOCK)
                log.info("tmux PTY '%s' started (pid=%d)", name, self.pid)
        else:
            # Raw PTY fallback
            self.pid, self.fd = pty.fork()
            if self.pid == 0:
                os.chdir(self.cwd)
                os.execvpe(cmd[0], cmd, env)
            else:
                self._alive = True
                flags = fcntl.fcntl(self.fd, fcntl.F_GETFL)
                fcntl.fcntl(self.fd, fcntl.F_SETFL, flags | os.O_NONBLOCK)
                log.info("PTY '%s' started (pid=%d)", name, self.pid)

    def append_replay(self, data: bytes):
        self.replay_buffer.extend(data)
        if len(self.replay_buffer) > REPLAY_BUFFER_SIZE:
            self.replay_buffer = self.replay_buffer[-REPLAY_BUFFER_SIZE:]

    def get_replay(self) -> str:
        return self.replay_buffer.decode("utf-8", errors="replace")

    def resize(self, cols: int, rows: int):
        if self.fd >= 0:
            try:
                fcntl.ioctl(self.fd, termios.TIOCSWINSZ, struct.pack("HHHH", rows, cols, 0, 0))
            except OSError:
                pass

    def write(self, data: bytes):
        if self.fd >= 0 and self._alive:
            try:
                os.write(self.fd, data)
            except OSError:
                self._alive = False

    def is_alive(self) -> bool:
        if not self._alive:
            return False
        try:
            pid, _ = os.waitpid(self.pid, os.WNOHANG)
            if pid != 0:
                self._alive = False
        except ChildProcessError:
            self._alive = False
        # For tmux sessions, also check if the tmux session itself is alive
        if not self._alive and self.uses_tmux:
            return tmux_session_exists(self.name)
        return self._alive

    def kill(self):
        self._alive = False
        if self.fd >= 0:
            try:
                os.close(self.fd)
            except OSError:
                pass
            self.fd = -1
        if self.pid > 0:
            try:
                os.kill(self.pid, signal.SIGTERM)
                for _ in range(30):
                    pid, _ = os.waitpid(self.pid, os.WNOHANG)
                    if pid != 0:
                        break
                    time.sleep(0.1)
                else:
                    try:
                        os.kill(self.pid, signal.SIGKILL)
                        os.waitpid(self.pid, 0)
                    except (OSError, ChildProcessError):
                        pass
            except (OSError, ChildProcessError):
                pass
        # Also kill the tmux session
        if self.uses_tmux:
            tmux_kill_session(self.name)
        log.info("PTY '%s' killed", self.name)


class SessionPool:
    def __init__(self):
        self.sessions: dict[str, PtySession] = {}

    def spawn(self, key: str, cmd: list[str], cwd: str = None, env_extra: dict = None) -> PtySession:
        if key in self.sessions:
            old = self.sessions[key]
            # Just detach the old PTY, don't kill tmux session if re-attaching
            old._alive = False
            if old.fd >= 0:
                try:
                    os.close(old.fd)
                except OSError:
                    pass
                old.fd = -1
            if old.pid > 0:
                try:
                    os.kill(old.pid, signal.SIGTERM)
                except (OSError, ChildProcessError):
                    pass
        try:
            session = PtySession(key, cmd, cwd, env_extra)
        except Exception:
            self.sessions.pop(key, None)
            raise
        self.sessions[key] = session
        return session

    def get(self, key: str) -> PtySession | None:
        s = self.sessions.get(key)
        if s and not s.is_alive():
            del self.sessions[key]
            return None
        return s

    def kill(self, key: str) -> bool:
        s = self.sessions.pop(key, None)
        if s:
            s.kill()
            return True
        return False

    def list_names(self) -> list[str]:
        # Include tmux sessions that aren't yet attached
        attached = set()
        dead = []
        for k, s in self.sessions.items():
            if not s.is_alive():
                dead.append(k)
            else:
                attached.add(k)
        for k in dead:
            del self.sessions[k]

        # Discover tmux sessions not yet in our pool
        if HAS_TMUX:
            for name in tmux_list_sessions():
                if name not in attached:
                    attached.add(name)

        return sorted(attached)

    def kill_all(self):
        for s in self.sessions.values():
            s.kill()
        self.sessions.clear()


pool = SessionPool()


def build_session_cmd(name: str, agents: dict) -> tuple[list[str], str]:
    """Build the command and working directory for a session.

    If `name` matches an agent in agents.json, launches Claude Code with
    the agent's system prompt and MCP config. Otherwise, launches a plain shell.

    Returns:
        (cmd, cwd) — command list and working directory path.
    """
    cfg = agents.get(name)
    if cfg:
        cmd = ["claude"]
        if cfg.get("prompt"):
            cmd.extend(["--system-prompt", cfg["prompt"]])
        if cfg.get("mcp_config"):
            mcp_path = cfg["mcp_config"]
            if os.path.exists(mcp_path):
                cmd.extend(["--mcp-config", mcp_path])
        cwd = cfg.get("cwd", os.path.expanduser("~"))
    else:
        # No agent match — plain shell session
        default_shell = "/bin/zsh" if platform.system() == "Darwin" else "/bin/bash"
        cmd = [os.environ.get("SHELL", default_shell)]
        cwd = os.path.expanduser("~")
    return cmd, cwd


# xterm.js sends DA1 queries (\x1b[c) on init. The terminal responds with
# \x1b[?1;2c etc., which can leak through as visible ghost text in the prompt.
# We strip these from PTY output before sending to the client.
_DA_RESPONSE_RE = re.compile(rb'\x1b\[\?[0-9;]*c')

def _blocking_read(fd: int) -> bytes:
    """Read from PTY fd with batching — collect available data up to 64KB."""
    if fd < 0:
        return b""
    try:
        r, _, _ = select.select([fd], [], [], 0.05)
        if not r:
            return b""
        chunks = []
        total = 0
        while total < 65536:
            try:
                chunk = os.read(fd, 65536 - total)
                if not chunk:
                    break
                chunks.append(chunk)
                total += len(chunk)
                r, _, _ = select.select([fd], [], [], 0)
                if not r:
                    break
            except (OSError, BlockingIOError):
                break
        data = b"".join(chunks)
        # Strip Device Attribute responses that leak as visible text
        data = _DA_RESPONSE_RE.sub(b'', data)
        return data
    except (OSError, ValueError):
        pass
    return b""



async def _reap_loop():
    """Periodically reap dead sessions."""
    while True:
        pool.list_names()
        await asyncio.sleep(15)


# ── Auth helper for REST endpoints ────────────────────

def _check_auth(request: Request) -> bool:
    token = request.headers.get("Authorization", "").replace("Bearer ", "")
    if not token:
        token = request.query_params.get("token", "")
    return users.verify_web_token(token)


# ── Routes ────────────────────────────────────────────

@app.get("/")
async def index():
    return RedirectResponse("/static/terminal.html")


@app.get("/office")
async def office():
    html_path = os.path.join(os.path.dirname(__file__), "static", "office.html")
    return FileResponse(html_path)


def _cwd_to_transcript_dir(cwd: str) -> str:
    """Convert agent cwd to Claude transcript directory path."""
    encoded = cwd.replace("/", "-")
    return os.path.expanduser(f"~/.claude/projects/{encoded}")


def _get_office_agents():
    """Build agent state snapshot from agents.json."""
    agents_data = load_agents()
    result = []
    for short_name, cfg in agents_data.items():
        cwd = cfg.get("cwd", "")
        transcript_dir = _cwd_to_transcript_dir(cwd) if cwd else ""
        result.append({
            "short_name": short_name,
            "name": short_name.capitalize(),
            "role": cfg.get("description", "")[:60],
            "cwd": cwd,
            "transcript_dir": transcript_dir,
            "activity": "idle",
            "current_tool": None,
            "task_id": None,
            "task_title": None,
        })
    return result


class AgentActivityTracker:
    """Watches Claude Code JSONL transcripts to detect tool_use events."""

    TOOL_ANIMATION = {
        "Write": "typing", "Edit": "typing", "NotebookEdit": "typing",
        "Read": "reading", "Glob": "reading", "Grep": "reading", "LS": "reading",
        "Bash": "running", "BashOutput": "running",
        "WebSearch": "searching", "WebFetch": "searching",
    }
    IDLE_TIMEOUT = 5.0  # seconds

    def __init__(self):
        self._positions = {}   # transcript_path -> file byte offset
        self._last_event = {}  # short_name -> timestamp
        self._state = {}       # short_name -> {"activity": str, "tool": str|None}

    def _find_latest_jsonl(self, transcript_dir: str):
        """Return path to most recently modified .jsonl in transcript_dir."""
        if not os.path.isdir(transcript_dir):
            return None
        files = glob_mod.glob(os.path.join(transcript_dir, "*.jsonl"))
        if not files:
            return None
        return max(files, key=os.path.getmtime)

    def _read_new_lines(self, path: str) -> list:
        """Read only new lines since last read (tail -f style)."""
        pos = self._positions.get(path, 0)
        try:
            with open(path, "rb") as f:
                f.seek(0, 2)
                end = f.tell()
                if end < pos:
                    pos = 0  # file rotated/truncated, restart from beginning
                f.seek(pos)
                data = f.read()
            self._positions[path] = end
            return data.decode("utf-8", errors="ignore").splitlines()
        except Exception:
            return []

    def poll(self, agents: list) -> list:
        """Poll all agents, return updated state list with activity fields."""
        now = time.time()
        updated = []
        for agent in agents:
            short_name = agent["short_name"]
            transcript_dir = agent.get("transcript_dir", "")

            path = self._find_latest_jsonl(transcript_dir) if transcript_dir else None
            tool_found = None

            if path:
                lines = self._read_new_lines(path)
                for line in lines:
                    try:
                        d = json.loads(line)
                        if d.get("type") == "assistant":
                            content = d.get("message", {}).get("content", [])
                            for c in content:
                                if c.get("type") == "tool_use":
                                    tool_found = c.get("name")
                                    break
                    except Exception:
                        pass

            if tool_found:
                self._last_event[short_name] = now
                activity = self.TOOL_ANIMATION.get(tool_found, "working")
                self._state[short_name] = {"activity": activity, "tool": tool_found}
            else:
                last = self._last_event.get(short_name, 0)
                if now - last > self.IDLE_TIMEOUT:
                    self._state[short_name] = {"activity": "idle", "tool": None}

            state = self._state.get(short_name, {"activity": "idle", "tool": None})
            updated.append({**agent, "activity": state["activity"], "current_tool": state["tool"]})

        return updated


_activity_tracker = AgentActivityTracker()
_office_clients: set = set()


@app.get("/api/office/agents")
async def office_agents():
    return {"agents": _get_office_agents()}


@app.post("/api/auth")
async def auth_endpoint(request: Request):
    """Exchange Telegram initData for a short-lived session token.

    The client sends the raw initData string from window.Telegram.WebApp.initData.
    We validate it server-side using the bot token (cannot be forged without it).
    Only the owner gets a token back.
    """
    try:
        body = await request.json()
    except Exception:
        return JSONResponse({"error": "Invalid JSON"}, status_code=400)

    init_data = body.get("initData", "")
    if not users.verify_init_data(init_data):
        return JSONResponse({"error": "Unauthorized"}, status_code=401)

    return {"token": users.make_web_token()}


@app.get("/health")
async def health():
    tmux_sessions = tmux_list_sessions() if HAS_TMUX else []
    return {
        "status": "ok",
        "sessions": len(pool.list_names()),
        "tmux_sessions": tmux_sessions,
        "tmux_available": HAS_TMUX,
        "uptime": round(time.time() - START_TIME),
    }


# ── File upload/download ─────────────────────────────

_HOME = Path(os.path.expanduser("~")).resolve()


def _safe_path(path: str, base: Path | None = None) -> Path | None:
    """Resolve path and verify it stays within the home directory."""
    root = base or _HOME
    p = Path(path) if path else root
    if not p.is_absolute():
        p = _HOME / p
    p = p.resolve()
    try:
        p.relative_to(_HOME)
    except ValueError:
        return None
    return p


@app.post("/api/upload")
async def upload_file(request: Request, file: UploadFile = File(...), path: str = Form("")):
    if not _check_auth(request):
        return JSONResponse({"error": "Unauthorized"}, status_code=401)

    target_dir = _safe_path(path) if path else UPLOAD_DIR.resolve()
    if target_dir is None:
        return JSONResponse({"error": "Path outside home directory"}, status_code=400)
    target_dir.mkdir(parents=True, exist_ok=True)

    # Sanitize filename
    safe_name = Path(file.filename).name
    if not safe_name or safe_name.startswith('.'):
        return JSONResponse({"error": "Invalid filename"}, status_code=400)

    target = target_dir / safe_name
    content = await file.read()
    target.write_bytes(content)

    return {"ok": True, "path": str(target), "size": len(content)}


@app.get("/api/download")
async def download_file(request: Request, path: str = ""):
    if not _check_auth(request):
        return JSONResponse({"error": "Unauthorized"}, status_code=401)

    if not path:
        return JSONResponse({"error": "No path specified"}, status_code=400)

    file_path = _safe_path(path)
    if file_path is None:
        return JSONResponse({"error": "Path outside home directory"}, status_code=400)

    if not file_path.exists() or not file_path.is_file():
        return JSONResponse({"error": "File not found"}, status_code=404)

    return FileResponse(file_path, filename=file_path.name)


@app.get("/api/browse")
async def browse_dir(request: Request, path: str = ""):
    if not _check_auth(request):
        return JSONResponse({"error": "Unauthorized"}, status_code=401)

    dir_path = _safe_path(path) if path else _HOME
    if dir_path is None:
        return JSONResponse({"error": "Path outside home directory"}, status_code=400)

    if not dir_path.exists() or not dir_path.is_dir():
        return JSONResponse({"error": "Directory not found"}, status_code=404)

    entries = []
    try:
        for entry in sorted(dir_path.iterdir()):
            if entry.name.startswith('.'):
                continue
            entries.append({
                "name": entry.name,
                "is_dir": entry.is_dir(),
                "size": entry.stat().st_size if entry.is_file() else 0,
            })
    except PermissionError:
        return JSONResponse({"error": "Permission denied"}, status_code=403)

    return {"path": str(dir_path), "entries": entries[:200]}


# ── WebSocket ─────────────────────────────────────────

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()

    # First message must be auth
    try:
        raw = await asyncio.wait_for(websocket.receive_text(), timeout=10)
        msg = json.loads(raw)
        if msg.get("type") != "auth" or not users.verify_web_token(msg.get("token", "")):
            await websocket.close(code=4001, reason="Unauthorized")
            return
    except (asyncio.TimeoutError, Exception):
        await websocket.close(code=4001, reason="Auth timeout")
        return

    agents = load_agents()
    attached_session: str | None = None
    reader_task: asyncio.Task | None = None
    ping_task: asyncio.Task | None = None

    async def read_pty(session_key: str):
        loop = asyncio.get_running_loop()
        while True:
            session = pool.get(session_key)
            if not session:
                # For tmux, try to re-attach if the session still exists
                if HAS_TMUX and tmux_session_exists(session_key):
                    agents_data = load_agents()
                    cmd, cwd = build_session_cmd(session_key, agents_data)
                    try:
                        session = pool.spawn(session_key, cmd, cwd)
                    except Exception:
                        pass
                if not session:
                    try:
                        await websocket.send_json({
                            "type": "killed",
                            "session": session_key,
                            "sessions": pool.list_names(),
                        })
                    except Exception:
                        pass
                    break
            try:
                data = await loop.run_in_executor(None, _blocking_read, session.fd)
                if data:
                    session.append_replay(data)
                    await websocket.send_json({
                        "type": "output",
                        "session": session_key,
                        "data": data.decode("utf-8", errors="replace"),
                    })
            except Exception:
                break

    async def ping_loop():
        """Send ping every 20 seconds to detect dead connections."""
        try:
            while True:
                await asyncio.sleep(20)
                try:
                    await websocket.send_json({"type": "ping"})
                except Exception:
                    break
        except asyncio.CancelledError:
            pass

    ping_task = asyncio.create_task(ping_loop())

    try:
        while True:
            raw = await websocket.receive_text()
            msg = json.loads(raw)
            msg_type = msg.get("type")

            if msg_type == "pong":
                continue

            elif msg_type == "list_sessions":
                await websocket.send_json({
                    "type": "sessions",
                    "sessions": pool.list_names(),
                    "tmux": HAS_TMUX,
                })

            elif msg_type == "list_agents":
                agents = load_agents()
                await websocket.send_json({
                    "type": "agents",
                    "agents": {n: {"description": c.get("description", "")} for n, c in agents.items()},
                })

            elif msg_type == "spawn":
                name = _sanitize_name(msg.get("session", ""))
                if not name:
                    await websocket.send_json({"type": "error", "message": "No session name"})
                    continue

                agents = load_agents()
                cmd, cwd = build_session_cmd(name, agents)

                try:
                    pool.spawn(name, cmd, cwd)
                except Exception as e:
                    await websocket.send_json({"type": "error", "message": str(e)})
                    continue

                attached_session = name
                if reader_task:
                    reader_task.cancel()
                reader_task = asyncio.create_task(read_pty(name))

                await websocket.send_json({
                    "type": "spawned",
                    "session": name,
                    "sessions": pool.list_names(),
                })

            elif msg_type == "attach":
                name = msg.get("session", "")
                session = pool.get(name)

                # Auto-reattach to tmux session if not in pool
                if not session and HAS_TMUX and tmux_session_exists(name):
                    agents_data = load_agents()
                    cmd, cwd = build_session_cmd(name, agents_data)
                    try:
                        session = pool.spawn(name, cmd, cwd)
                    except Exception:
                        pass

                if not session:
                    await websocket.send_json({"type": "error", "message": f"Session '{name}' not found"})
                    continue

                attached_session = name
                if reader_task:
                    reader_task.cancel()
                reader_task = asyncio.create_task(read_pty(name))

                replay = session.get_replay()
                if replay:
                    await websocket.send_json({
                        "type": "replay",
                        "session": name,
                        "data": replay,
                    })

            elif msg_type == "input":
                name = msg.get("session", "") or attached_session
                session = pool.get(name) if name else None
                if session:
                    session.write(msg.get("data", "").encode("utf-8"))

            elif msg_type == "resize":
                name = msg.get("session", "") or attached_session
                session = pool.get(name) if name else None
                if session:
                    session.resize(msg.get("cols", 80), msg.get("rows", 24))

            elif msg_type == "kill":
                name = msg.get("session", "")
                pool.kill(name)
                if attached_session == name:
                    attached_session = None
                    if reader_task:
                        reader_task.cancel()
                        reader_task = None
                await websocket.send_json({
                    "type": "killed",
                    "session": name,
                    "sessions": pool.list_names(),
                })

    except WebSocketDisconnect:
        pass
    except Exception as e:
        log.error("WebSocket error: %s", e)
    finally:
        if reader_task:
            reader_task.cancel()
        if ping_task:
            ping_task.cancel()


def main():
    import uvicorn
    host = os.getenv("AGENTSTACK_HOST", "0.0.0.0")
    port = int(os.getenv("AGENTSTACK_PORT", "8765"))

    def _handle_signal(sig, frame):
        # Detach cleanly, don't kill tmux sessions
        for s in pool.sessions.values():
            s._alive = False
            if s.fd >= 0:
                try: os.close(s.fd)
                except OSError: pass
        sys.exit(0)

    signal.signal(signal.SIGTERM, _handle_signal)
    signal.signal(signal.SIGINT, _handle_signal)

    print("=" * 40)
    print("  AgentStack Terminal Server")
    print("=" * 40)
    print(f"  http://{host}:{port}")
    print(f"  Owner: {users.OWNER_ID}")
    print(f"  tmux:  {'yes' if HAS_TMUX else 'no (sessions wont persist)'}")
    existing = tmux_list_sessions() if HAS_TMUX else []
    if existing:
        print(f"  Existing sessions: {', '.join(existing)}")
    print()
    uvicorn.run(app, host=host, port=port, log_level="info")


if __name__ == "__main__":
    main()
